# Generated by Django 3.2 on 2021-04-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Purchase Date')),
                ('purchase_price', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crypto')),
            ],
        ),
    ]
