# Generated by Django 3.2 on 2021-04-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date']},
        ),
    ]
