# Generated by Django 3.2 on 2021-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210426_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='feelings',
            field=models.ManyToManyField(to='main_app.Feelings'),
        ),
    ]
